// Regenerates src/lib/api/schema.d.ts from the hub API's OpenAPI document.
//
// The document comes from `evo-agents hub openapi` run against this checkout (the repository root is put first on
// PYTHONPATH, so an editable install pointing elsewhere does not leak in). CI runs this script and fails when the
// committed schema.d.ts differs from its output. Set PYTHON to choose the interpreter; it needs the hub-server extra.
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const webDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(webDir, "..");
const target = path.join(webDir, "src", "lib", "api", "schema.d.ts");

const HEADER = `/**
 * Generated by \`pnpm gen:api\` from \`evo-agents hub openapi\`. Do not edit by hand:
 * change the FastAPI models in evo_agents/hub/server and run \`pnpm gen:api\` again.
 */

`;

function runOpenapi(python) {
  const env = { ...process.env, PYTHONPATH: [repoRoot, process.env.PYTHONPATH].filter(Boolean).join(path.delimiter) };
  return spawnSync(python, ["-m", "evo_agents", "hub", "openapi"], {
    cwd: repoRoot,
    env,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
}

function openapiDocument() {
  const candidates = process.env.PYTHON ? [process.env.PYTHON] : ["python3", "python"];
  for (const python of candidates) {
    const result = runOpenapi(python);
    if (result.error && result.error.code === "ENOENT") continue;
    if (result.status !== 0) {
      process.stderr.write(result.stderr ?? "");
      throw new Error(`${python} -m evo_agents hub openapi exited with status ${result.status}`);
    }
    return JSON.parse(result.stdout);
  }
  throw new Error(`no Python interpreter found (tried ${candidates.join(", ")}); set PYTHON`);
}

const ast = await openapiTS(openapiDocument());
mkdirSync(path.dirname(target), { recursive: true });
writeFileSync(target, HEADER + astToString(ast), "utf8");
console.log(`wrote ${path.relative(webDir, target)}`);
