"""The metadata of ``evo_agents.hub.tables`` is the schema the migrations make.

Alembic's ``compare_metadata``, comparing types and server defaults, finds no difference on a database migrated to
head, procrastinate's tables aside; the migration environment autogenerates from that metadata and finds nothing to
do. What Alembic compares: tables, columns, types, nullability, server defaults, identities, primary, unique and
foreign keys, and indexes with their columns, expressions and order. What it does not: CHECK constraints, triggers
and the WHERE of a partial index, which the migrations alone hold (``tests.hub.test_migrate`` and
``tests.hub.test_run_tables`` exercise them).
"""

import warnings

import pytest

from tests.hub import pg

if not pg.DSN:
    pytest.skip(pg.SKIP_REASON, allow_module_level=True)

import psycopg
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool

from evo_agents.hub import tables
from evo_agents.hub.migrate import alembic_config, migrate
from tests.hub.test_migrate import TABLES

# Alembic compares a generated column's expression as text and warns at the casts Postgres adds to it.
GENERATED_COLUMN_WARNING = "memories.search"


def engine_on(db):
    return create_engine("postgresql+psycopg://", creator=lambda: psycopg.connect(db.dsn), poolclass=NullPool)


def include_name(name, type_, parent_names) -> bool:
    return not (type_ == "table" and name.startswith("procrastinate_"))


def test_the_metadata_holds_the_forty_five_hub_tables():
    assert set(tables.metadata.tables) == TABLES - pg.QUEUE_TABLES
    assert len(tables.metadata.tables) == 45


def test_the_metadata_matches_the_schema_at_head(hub_db):
    migrate(hub_db.dsn)
    engine = engine_on(hub_db)
    try:
        with engine.connect() as conn, warnings.catch_warnings(record=True) as warned:
            warnings.simplefilter("always")
            context = MigrationContext.configure(
                conn,
                opts={"compare_type": True, "compare_server_default": True, "include_name": include_name},
            )
            diff = compare_metadata(context, tables.metadata)
    finally:
        engine.dispose()
    assert diff == []
    assert [str(w.message) for w in warned if GENERATED_COLUMN_WARNING not in str(w.message)] == []


@pytest.mark.filterwarnings(f"ignore:Computed default on {GENERATED_COLUMN_WARNING}")
def test_autogenerate_reads_the_metadata_and_finds_nothing_to_do(hub_db):
    migrate(hub_db.dsn)
    config = alembic_config()
    engine = engine_on(hub_db)
    try:
        with engine.connect() as conn:
            config.attributes["connection"] = conn
            command.check(config)  # AutogenerateDiffsDetected on any difference
    finally:
        engine.dispose()
