"""The digest of a Claude Code session, built on the machine from its transcript (``evo_agents.hub.digest``), and the
Stop hook's side of pushing it (``evo_agents.hub.hooks``) where no hub is needed.

The digest counts messages as the harness-engineering skill's digest does (meta lines and lines of other types left
out, fewer than 6 means no digest), counts calls and failures per tool and per Bash program, keeps what the person wrote
and the text of failed results, cut, counts the tokens of each message of the model once, and names the model most
messages name. The hook sends nothing in a worker run, nothing when not signed in, nothing for a session under 6
messages, and when the hub does not answer it keeps the digest waiting and leaves the hub alone for the cooldown.
``tests.hub.test_session_digests`` pushes digests to a hub on Postgres."""

import io
import json
import sys
from pathlib import Path

import pytest

from evo_agents.cli import main
from evo_agents.hub import client as hub_client
from evo_agents.hub import digest, hooks
from evo_agents.hub.digest import DigestState, build, fingerprint, program
from tests.hub import pg

SESSION = "0199b1c2-7d3e-7a10-9c41-5e2f3a4b5c6d"
MODEL = "claude-opus-5-5"
USAGE = {"input_tokens": 10, "output_tokens": 20, "cache_creation_input_tokens": 300, "cache_read_input_tokens": 4000}
FAILED_TEST = "FAILED tests/test_queue.py::test_claim - AssertionError: assert 2 == 1"


def at(second: int) -> str:
    return f"2026-10-08T01:00:{second:02d}.000Z"


def said(text: str, second: int, **extra) -> dict:
    return {"type": "user", "message": {"role": "user", "content": text}, "timestamp": at(second), **extra}


def answered(message_id: str, second: int, *content: dict, model: str = MODEL) -> dict:
    message = {"id": message_id, "role": "assistant", "model": model, "content": list(content), "usage": USAGE}
    return {"type": "assistant", "message": message, "timestamp": at(second)}


def tool_use(call_id: str, name: str, **given) -> dict:
    return {"type": "tool_use", "id": call_id, "name": name, "input": given}


def result(call_id: str, second: int, text: str = "ok", error: bool = False) -> dict:
    block = {"type": "tool_result", "tool_use_id": call_id, "content": text, "is_error": error}
    return {"type": "user", "message": {"role": "user", "content": [block]}, "timestamp": at(second)}


def session_lines(turn: str = "Run the tests and fix what fails.", command: str = "python -m pytest -q") -> list[dict]:
    """A session of 13 messages: a test run that fails, a read, an edit, the test run again, a git push that fails."""
    return [
        said("<local-command-caveat>Caveat: the messages below were generated by the user</local-command-caveat>", 0)
        | {"isMeta": True},
        said(turn, 1),
        answered("msg_1", 2, {"type": "text", "text": "Running the tests."}),
        answered("msg_1", 3, tool_use("toolu_1", "Bash", command=f"cd /work/app && {command}")),
        result("toolu_1", 4, FAILED_TEST, error=True),
        answered("msg_2", 5, tool_use("toolu_2", "Read", file_path="/work/app/queue.py")),
        result("toolu_2", 6, "def claim(): ..."),
        answered(
            "msg_3", 7, tool_use("toolu_3", "Edit", file_path="/work/app/queue.py", old_string="a", new_string="b")
        ),
        result("toolu_3", 8),
        answered("msg_4", 9, tool_use("toolu_4", "Bash", command=f"cd /work/app && {command}")),
        result("toolu_4", 10, "12 passed"),
        answered("msg_5", 11, tool_use("toolu_5", "Bash", command="git -C /work/app push")),
        result("toolu_5", 12, "rejected: non-fast-forward", error=True),
        {"type": "system", "subtype": "compact_boundary", "timestamp": at(13)},
        {"type": "file-history-snapshot", "snapshot": {}},
        said("<command-name>/cost</command-name>", 14),
    ]


def write_transcript(path: Path, lines: list[dict]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(json.dumps(line) + "\n" for line in lines) + "not json\n", encoding="utf-8")
    return path


# Building the digest


def test_the_digest_counts_messages_as_harness_digest_does_and_needs_six(tmp_path):
    lines = session_lines()
    found = build(write_transcript(tmp_path / "s.jsonl", lines), "/work/app")
    assert found["messages"] == 13  # 16 lines: the meta line and the two of other types do not count
    short = [line for line in lines if line.get("type") in ("user", "assistant") and not line.get("isMeta")][:5]
    assert build(write_transcript(tmp_path / "short.jsonl", short), "/work/app") is None
    assert build(tmp_path / "missing.jsonl", "/work/app") is None


def test_the_digest_holds_tools_programs_turns_errors_model_and_tokens(tmp_path):
    found = build(write_transcript(tmp_path / "s.jsonl", session_lines()), "/work/app")
    assert found["cwd"] == "/work/app"
    assert (found["started_at"], found["ended_at"]) == ("2026-10-08T01:00:01+00:00", "2026-10-08T01:00:14+00:00")
    assert found["model"] == MODEL and found["models"] == [{"model": MODEL, "messages": 5}]
    assert found["usage"] == {name: value * 5 for name, value in USAGE.items()}, "a message's lines count once"
    assert found["tools"] == [
        {"gen_ai.tool.name": "Bash", "calls": 3, "errors": 2},
        {"gen_ai.tool.name": "Edit", "calls": 1, "errors": 0},
        {"gen_ai.tool.name": "Read", "calls": 1, "errors": 0},
    ]
    assert found["bash"] == [
        {"program": "python -m pytest", "calls": 2, "errors": 1},
        {"program": "git push", "calls": 1, "errors": 1},
    ]
    assert found["user_turns"] == ["Run the tests and fix what fails."], "text in <...> is not the person's"
    assert found["commands"] == ["cd /work/app && python -m pytest -q", "git -C /work/app push"]
    assert found["repeated_commands"] == [{"command": "cd /work/app && python -m pytest -q", "n": 2}]
    assert found["errors"] == [
        {"gen_ai.tool.name": "Bash", "text": FAILED_TEST, "n": 1},
        {"gen_ai.tool.name": "Bash", "text": "rejected: non-fast-forward", "n": 1},
    ]
    assert (found["files_read"], found["files_edited"]) == (1, ["/work/app/queue.py"])


def test_the_digest_cuts_long_text_and_bounds_its_lists(tmp_path):
    lines = session_lines(turn="x" * 5000, command="echo " + "y" * 5000)
    lines += [said(f"turn {n}", 20) for n in range(60)]
    found = build(write_transcript(tmp_path / "s.jsonl", lines), "/work/app")
    assert len(found["user_turns"]) == digest.MAX_USER_TURNS
    assert len(found["user_turns"][0]) == digest.USER_TURN_CHARS and found["user_turns"][0].endswith("...")
    assert all(len(command) <= digest.COMMAND_CHARS for command in found["commands"])


def test_a_digest_has_one_fingerprint_for_one_content(tmp_path):
    first = build(write_transcript(tmp_path / "a.jsonl", session_lines()), "/work/app")
    again = build(write_transcript(tmp_path / "b.jsonl", session_lines()), "/work/app")
    longer = build(write_transcript(tmp_path / "c.jsonl", [*session_lines(), said("One more thing.", 30)]), "/w")
    assert fingerprint(first) == fingerprint(again) != fingerprint(longer)


@pytest.mark.parametrize(
    "command, expected",
    [
        ("git -C ~/x status --short", "git status"),
        ("cd /a && FOO=1 python -m pytest -q", "python -m pytest"),
        ("uv run pytest", "uv run"),
        ("ls -la | head", "ls"),
        ("export A=1; npm test", "npm test"),
        ("sudo /usr/bin/make install", "make install"),
        ("ruff check .", "ruff"),
        ("cd /tmp", None),
        ("", None),
    ],
)
def test_the_program_of_a_bash_digest_command(command, expected):
    assert program(command) == expected


def test_the_digest_state_keeps_sessions_per_hub_and_forgets_old_ones(tmp_path):
    state = DigestState(tmp_path, "https://hub.test")
    state.put("old", {"transcript": "/t/old.jsonl", "pending": True}, now=1_000.0)
    state.put("new", {"transcript": "/t/new.jsonl", "pending": True}, now=2_000.0)
    state.put("done", {"transcript": "/t/done.jsonl", "pending": False}, now=3_000.0)
    assert [key for key, _ in state.waiting("new", 3)] == ["old"]
    assert [key for key, _ in state.waiting("someone", 1)] == ["old"]
    assert DigestState(tmp_path, "https://other.test").sessions() == {}
    state.put("later", {"pending": False}, now=1_000.0 + digest.KEEP_SECONDS + 1)
    assert set(state.sessions()) == {"new", "done", "later"}, "a session not pushed for 90 days is forgotten"
    (tmp_path / digest.STATE_FILE).write_text("{broken", encoding="utf-8")
    assert state.sessions() == {}


# The Stop hook, without a hub


@pytest.fixture
def home(tmp_path, monkeypatch) -> Path:
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    for variable in ("CLAUDE_CONFIG_DIR", "CLAUDE_PROJECT_DIR", "EVO_KG_PROJECT", "EVO_KG_HOME", hooks.RUN_VARIABLE):
        monkeypatch.delenv(variable, raising=False)
    return home


@pytest.fixture
def sent(monkeypatch) -> list:
    """Every request a hook sends, recorded; each still goes out."""
    requests = []
    real = hub_client._send

    def recording(method, url, headers, data, timeout):
        requests.append((method, url))
        return real(method, url, headers, data, timeout)

    monkeypatch.setattr(hub_client, "_send", recording)
    return requests


def signed_in(home: Path, url: str) -> None:
    directory = home / ".evo" / "hub"
    directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    (directory / "token").write_text("evo_test_token_never_printed\n", encoding="utf-8")
    (directory / "config.json").write_text(json.dumps({"url": url, "login": "alice"}), encoding="utf-8")


def stop(payload: dict, monkeypatch, capsys) -> tuple[int, str, str]:
    monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(payload)))
    code = main(["hub", "hook", "stop"])
    out, err = capsys.readouterr()
    return code, out, err


def payload(home: Path, lines: list[dict]) -> dict:
    work = home / "work"
    transcript = write_transcript(home / ".claude" / "projects" / "-work" / f"{SESSION}.jsonl", lines)
    return {"session_id": SESSION, "transcript_path": str(transcript), "cwd": str(work), "hook_event_name": "Stop"}


def test_stop_sends_no_digest_when_not_signed_in_in_a_worker_run_or_under_six_messages(home, monkeypatch, capsys, sent):
    given = payload(home, session_lines())
    assert stop(given, monkeypatch, capsys) == (0, "", "")  # not signed in
    signed_in(home, f"http://127.0.0.1:{pg.free_port()}")
    monkeypatch.setenv(hooks.RUN_VARIABLE, "7")
    assert stop(given, monkeypatch, capsys) == (0, "", "")  # the agent of run #7: its trace is on the hub
    monkeypatch.delenv(hooks.RUN_VARIABLE)
    assert stop(payload(home, session_lines()[:6]), monkeypatch, capsys) == (0, "", "")  # 5 messages
    for broken in ({**given, "session_id": "../etc"}, {**given, "transcript_path": "relative.jsonl"}):
        assert stop(broken, monkeypatch, capsys) == (0, "", "")
    assert sent == [] and not (home / ".evo" / "hub" / digest.STATE_FILE).exists()


def test_a_digest_the_hub_did_not_take_waits_and_the_hub_is_left_alone(home, monkeypatch, capsys, sent):
    url = f"http://127.0.0.1:{pg.free_port()}"
    signed_in(home, url)
    clock = [1_000_000.0]
    monkeypatch.setattr(hooks, "_now", lambda: clock[0])
    given = payload(home, session_lines())
    code, out, err = stop(given, monkeypatch, capsys)
    assert (code, out) == (0, "") and len(sent) == 1  # the projects, to tell the session's: refused
    assert err.startswith("evo-hub: session digest not pushed, the hub did not answer") and err.count("\n") == 1
    assert "evo_test_token" not in err
    waiting = DigestState(home / ".evo" / "hub", url).get(SESSION)
    assert waiting["pending"] is True and waiting["transcript"] == given["transcript_path"]
    assert "sha256" not in waiting and "resolved" not in waiting

    clock[0] += hooks.COOLDOWN - 1
    assert stop(given, monkeypatch, capsys) == (0, "", "") and len(sent) == 1  # not asked again yet
    assert DigestState(home / ".evo" / "hub", url).get(SESSION)["pending"] is True
